### ISSUE TITLE
[feature] Permalink to specific SQL query/chart configuration

### ISSUE THREAD

**Issue by casidiablo** [hydrosquall/datasette-nteract-data-explorer#18]
This plugin is awesome.

It would be great if the chart configuration was in the URL too. That way you can share a link that does both: run the sql query AND renders a customized chart.

Right now when you create a chart, if you refresh the page you will lose any changes you made to the chart.

**Comment by hydrosquall** [comment]
Thanks @casidiablo ! I think this is a good idea and should be doable. I'll look into it.

**Comment by hydrosquall** [comment]
@casidiablo this works now was of version 0.4.1. https://pypi.org/project/datasette-nteract-data-explorer/0.4.1/

Example [link to a hexbin graph](https://datasette-nteract-data-explorer-23lah3ulx.vercel.app/happy_planet_index/hpi_cleaned#dataExplorer.metadata=%7B%22dx%22%3A%7B%22view%22%3A%22hexbin%22%2C%22lineType%22%3A%22line%22%2C%22areaType%22%3A%22hexbin%22%2C%22selectedDimensions%22%3A%5B%22Region%22%5D%2C%22selectedMetrics%22%3A%5B%5D%2C%22pieceType%22%3A%22bar%22%2C%22summaryType%22%3A%22violin%22%2C%22networkType%22%3A%22force%22%2C%22hierarchyType%22%3A%22dendrogram%22%2C%22trendLine%22%3A%22none%22%2C%22marginalGraphics%22%3A%22none%22%2C%22barGrouping%22%3A%22Clustered%22%2C%22colors%22%3A%5B%22%23DA752E%22%2C%22%23E5C209%22%2C%22%231441A0%22%2C%22%23B86117%22%2C%22%234D430C%22%2C%22%231DB390%22%2C%22%23B3331D%22%2C%22%23088EB2%22%2C%22%23417505%22%2C%22%23E479A8%22%2C%22%23F9F39E%22%2C%22%235782DC%22%2C%22%23EBA97B%22%2C%22%23A2AB60%22%2C%22%23B291CF%22%2C%22%238DD2C2%22%2C%22%23E6A19F%22%2C%22%233DC7E0%22%2C%22%2398CE5B%22%5D%2C%22chart%22%3A%7B%22metric1%22%3A%22rowid%22%2C%22metric2%22%3A%22AvrgLifeExpectancy%22%2C%22metric3%22%3A%22none%22%2C%22metric4%22%3A%22none%22%2C%22dim1%22%3A%22Region%22%2C%22dim2%22%3A%22Country%22%2C%22dim3%22%3A%22none%22%2C%22timeseriesSort%22%3A%22array-order%22%2C%22networkLabel%22%3A%22none%22%7D%7D%7D)

Feel free to add a link to https://github.com/hydrosquall/datasette-nteract-data-explorer/discussions/10 if you have a future public graphs or datasette deployments you'd like to share!
